### ISSUE TITLE
LibSpotify Log in unsuccessful

### ISSUE THREAD

**Issue by aquascop** [TheQwertiest/foo_spotify#38]
WebAPI Log in is ok, 
Component is well authorized on my spotify account approved application list (Foobar2000: foo_spotify)
but i do not succeed in Logging in with the 'Log in' button on the LibSpotify Area : it keeps the status : logged out

info : I have a spotify family account.

**Comment by TheQwertiest** [comment]
Please do the following:
- open fb2k console (view > console).
- open foo_spotify in fb2k preferences
- clear console
- try to login in LibSpotify
- paste console output here (use `insert code` button when doing so).

It might be caused by "family account" though: I'm not sure if it's supported by libspotify.

**Comment by aquascop** [comment]
Hi, for an unknown reason, log in is now successfull .  nothing has been changed since installation. stange, maybe a reaction time from spotify server to grant access ?
so libspotify is compatible with family account.
thanks for your support.

**Comment by cuno92** [comment]
dear @TheQwertiest I still has issue in version 1.1.3, here is the error log. Thanks!
`Opening track for playback: "spotify:track:4bHsxqR3GMrXTxEPLuK5ue"
foo_spotify (log): 10:16:44.940 I [c:/Users/spotify-buildagent/BuildAgent/work/1e0ce8a77adfb2dc/client/core/session/offline_authorizer.cpp:297] Unable to login offline: no such user
foo_spotify (log): 10:16:44.940 E [c:/Users/spotify-buildagent/BuildAgent/work/1e0ce8a77adfb2dc/client/core/network/proxy_resolver_win32.cpp:215] WinHttpGetProxyForUrl failed
foo_spotify (log): 10:16:44.967 I [ap:1752] Connecting to AP ap.gslb.spotify.com:4070
foo_spotify (log): 10:16:47.366 E [ap:1694] AP Socket Error: No connection could be made because the target machine actively refused it.  (10061)
foo_spotify (log): 10:16:47.366 E [ap:3915] Connection error:  101
foo_spotify (log): 10:16:47.366 I [ap:1752] Connecting to AP ap.gslb.spotify.com:80
foo_spotify (log): 10:16:49.765 E [ap:1694] AP Socket Error: No connection could be made because the target machine actively refused it.  (10061)
foo_spotify (log): 10:16:49.765 E [ap:3915] Connection error:  101
foo_spotify (log): 10:16:49.765 I [ap:1752] Connecting to AP ap.gslb.spotify.com:443
Timer timeout: foo_spotify: LibSpotify wait for login update
foo_spotify (log): 10:16:52.081 E [ap:1694] AP Socket Error: No connection could be made because the target machine actively refused it.  (10061)
foo_spotify (log): 10:16:52.081 E [ap:3915] Connection error:  101
foo_spotify (log): 10:16:52.081 I [ap:1752] Connecting to AP ap.gslb.spotify.com:4070
foo_spotify (log): 10:16:54.493 E [ap:1694] AP Socket Error: No connection could be made because the target machine actively refused it.  (10061)
foo_spotify (log): 10:16:54.493 E [ap:3915] Connection error:  101
foo_spotify (log): 10:16:54.493 I [ap:1752] Connecting to AP ap.gslb.spotify.com:80
foo_spotify (log): 10:16:56.822 E [ap:1694] AP Socket Error: No connection could be made because the target machine actively refused it.  (10061)
foo_spotify (log): 10:16:56.822 E [ap:3915] Connection error:  101
foo_spotify (log): 10:16:56.822 I [ap:1752] Connecting to AP ap.gslb.spotify.com:443
foo_spotify (log): 10:16:59.130 E [ap:1694] AP Socket Error: No connection could be made because the target machine actively refused it.  (10061)
foo_spotify (log): 10:16:59.130 E [ap:3915] Connection error:  101
Spotify Integration:
Failed to login:
Can not connect to Spotify`
